version: '3.8'
services:
  web:
    build: .
    command: python incident_management/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount the project directory to /app in the container
    ports:
      - "8000:8000"