services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key
      - DJANGO_ALLOWED_HOSTS=localhost
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge