# Generated by Django 5.0.2 on 2024-12-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
